# Generated by Django 3.0.7 on 2020-06-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200618_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='sumnail',
            field=models.ImageField(default='logo_Dabyss.png', upload_to='blog_sumnail/'),
        ),
        migrations.AddField(
            model_name='gamesarticle',
            name='sumnail',
            field=models.ImageField(default='logo_Dabyss.png', upload_to='game_sumnail/'),
        ),
    ]
